CREATE TABLE IF NOT EXISTS users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	furigana VARCHAR(50) NOT NULL,
	phone_number VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	enabled BOOLEAN NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	
);

CREATE TABLE IF NOT EXISTS tasks (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mydate DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    category_code VARCHAR(50) NOT NULL,
    done BOOLEAN NOT NULL,
    current_streak INT NOT NULL,
    max_streak INT NOT NULL,
    repeat_type VARCHAR(10) DEFAULT 'none',
    repeat_frequency VARCHAR(10) DEFAULT NULL,
    repeat_weekdays VARCHAR(50) DEFAULT NULL,
    repeat_month_day INT DEFAULT NULL
);
	